export const AUCTION_DETAIILS = 'AUCTION_DETAIILS';
export const AUCTION_DETAIILS_SUCCESS = 'AUCTION_DETAIILS_SUCCESS';

export const DEMO_AUCTION = 'DEMO_AUCTION';
export const DEMO_AUCTION_SUCCESS = 'DEMO_AUCTION_SUCCESS';    
